### ISSUE TITLE
Wrong example in Read the Docs page "Simple Test"

### ISSUE THREAD

**Issue by vin1953** [adafruit/Adafruit_CircuitPython_BluefruitConnect#38]
On this page [https://docs.circuitpython.org/projects/bluefruitconnect/en/latest/examples.html](https://docs.circuitpython.org/projects/bluefruitconnect/en/latest/examples.html)

The 5th block of example code is the same as the first. But the description states that it should be a combination of the first and additionally a "RawTextPacket" example. Looking at the files in the GitHub examples folder for this documentation I think you need to refer to "bluefruitconnect_simpletest2.py". Being barely able to comprehend Python and the libraries is enough of a struggle (embedded C for over 30 years, now retired). Having the documentation add to the confusion is really a pain!

Thanks in advance,
Vin...

This example demonstrates receiving both a color (as in simpletest above)
and raw text (using RawTextPacket).

.. literalinclude:: ../examples/**bluefruitconnect_simpletest.py**
    :caption: examples/**bluefruitconnect_simpletest.py**
    :linenos:

**Comment by tannewt** [comment]
@vin1953 Want to try making a PR to fix it? https://learn.adafruit.com/contribute-to-circuitpython-with-git-and-github

**Comment by vin1953** [comment]
It may take a little effort but, it's one more thing to learn. So, I guess I'll read through the stuff and try to make it happen.

**Comment by FoamyGuy** [comment]
resolved by #39
